language: python
python: 
  - "3.7"
services: 
  - postgresql
before_install: 
  - "cd server"
before_script: 
  - "psql -c 'create database testdb;' -U postgres"
  - "mkdir -p secrets && echo '{\"dbname\"\":\" \"testdb\", \"user\"\":\" \"postgres\"}' > secrets/testing.db.json"
install: 
  - "pip install -r requirements.txt"
script: 
  - green

