language: "python"
python:
    - "3.7"
services:
    - postgres
install:
    - pip install -r requirements.txt
script:
    - green

before_install:
    - cd server

before_script:
    - psql -c 'create database test-db;' -U postgres
    - mkdir -p secrets && echo '{"dbname": "test-db", "user": "postgres"}' > secrets/testing.db.json

